# ==============================================================================
# RECONSTRUCTION / DOCUMENTATION SCRIPT
# ==============================================================================
# Purpose:
#   Documents a reproducible implementation of the normalization,
#   PSI calculation, and exploratory PCA/residualization procedures
#   described or considered during manuscript revision.
#
# IMPORTANT:
#   This script is a newly written reconstruction/documentation artifact.
#   It is NOT claimed to be the original historical analysis script.
#
# Historical raw inputs, original model objects, original residualized
# matrices, and complete historical execution logs were not recovered.
#
# Therefore, outputs generated by this script must not be represented
# as the original outputs underlying the manuscript unless independently
# matched against archived results.
# ==============================================================================
